config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  get 'sessions/new'

  get '/', to: "home#top"
  
  get '/about', to: "home#about"
  
  resources :blogs do
    collection do
      post :confirm
    end
  end
  
  resources :users do
    collection do
      post :confirm
    end
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :favorites, only: [:create, :destroy]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :title, presence: true
    validates :content, presence: true
    validates :content, length: { maximum: 140 }  
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user
    mount_uploader :image, ImageUploader
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :employees, dependent: :destroy
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
     belongs_to :company
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true, length: { maximum: 30 }
    validates :email, presence: true, length: { maximum: 255 },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
     before_validation { email.downcase! }
     has_secure_password
     validates :password, presence: true, length: { minimum: 6 }
     has_many :blogs, dependent: :destroy
     has_many :favorites, dependent: :destroy
     mount_uploader :icon, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
   include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :login_check, only: [:new, :show, :edit, :update, :destroy]
  before_action :set_blog, only: [:show, :edit, :update,:destroy] 
  
  def index
    @blogs = Blog.all

  end

  def new
    if params[:back]
      @blog = Blog.new(blog_params)
      @blog.image.retrieve_from_cache! params[:cache][:image]
    else
      @blog = Blog.new
    end
  end
  
  def confirm
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    render :new if @blog.invalid?
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    @blog.image.retrieve_from_cache!  params[:cache][:image]
    
    if @blog.save
      BlogMailer.blog_mail(@blog).deliver
      redirect_to blogs_path, notice: "ブログを作成しました！"
    else
      render 'new'
    end
  end

  def show
    @blog = Blog.find(params[:id])
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  def edit
    @blog = Blog.find(params[:id])   
  end

  def update
    @blog = Blog.find(params[:id])   
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "ブログを編集しました！"
    else
      render 'edit'
    end
  end
  
  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"ブログを削除しました！"
  end
  

  private

  def blog_params
    params.require(:blog).permit(:title, :content, :image)
  end
  
  def set_blog
    @blog = Blog.find(params[:id])
  end
  
  def login_check
  if current_user.nil?
    flash[:notice] = "権限がありません"
    redirect_to "/sessions/new"
  end   
  end 
  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :content)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def create
        favorite = current_user.favorites.create(blog_id: params[:blog_id])
        redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
    end

    def destroy
        favorite = current_user.favorites.find_by(blog_id: params[:blog_id]).destroy
        redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
    end

    def index
        @favorites = Favorite.all
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end
  
  
  
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_user_infomation, only: [:edit, :update]
    def new
        @user = User.new
    end
    
    
    def confirm 
        @user = User.new(user_params)
        render :new if @user.invalid?
    end
    
    
    def create
        @user = User.new(user_params)
        @user.icon.retrieve_from_cache!  params[:cache][:image]
         
        if @user.save
            session[:user_id] = @user.id
            flash[:notice] = "ユーザー登録が完了しました"
            redirect_to user_path(@user.id)
        else
            render 'new'
        end
    end
    
    
    
    def show
        @user = User.find(params[:id])
        @favorites = @user.favorites
    end
    
    def update
        if @user.update(user_params)
            redirect_to user_path(@user.id), notice: "ユーザー情報を編集しました！"
        else
            render 'edit'
        end
    end


    private
    
    def set_user_infomation
      @user = User.find(params[:id])
    end
    
    def user_params
        params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :icon, :icon_cache)
    end
    
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
    def choose_new_or_edit
        if action_name == 'new' || action_name == 'confirm'
            confirm_blogs_path
            
        elsif action_name == 'edit'
            blog_path
            
        end
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    def logged_in?
        current_user.present?
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def user_choose_new_or_edit
      if action_name == 'new' || action_name == 'confirm'
          confirm_users_path

      elsif action_name == 'edit'
          user_path

      end
    end
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>
  
  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>



  <%= form.submit %>
<% end %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= hidden_field_tag :"cache[image]",@blog.image.cache_name %>

  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <p>
    <strong>Image:</strong>
    <%= image_tag(@blog.image.url) %>
  </p>
  <%= form.submit  "投稿する" %>
<% end %>

<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= hidden_field_tag :"cache[image]",@blog.image.cache_name %>
  <%= form.submit "もどる", name: 'back' %>
<% end %>

app/views/blogs/edit.html.erb
<h2>ブログを編集する</h2>

  <%= render 'form' %>

app/views/blogs/index.html.erb
<div class="text-center">
<% @blogs.each do |blog| %>
    <div class="blogs-index">
        <%= link_to blog.content, blog_path(blog.id) %>
      </div>
<% end %>
</table>
<br>
</div>

app/views/blogs/new.html.erb
<h2>ブログを作成する</h2>

<%= render 'form' %>

app/views/blogs/show.html.erb
<div class="text-center main posts-show">
    <div class="posts-show-item" >
    <h1>
        Title
    </h1>
    <h3>
        <%= @blog.title %>
    </h3>
    <h1>
        Content
    </h1>
    <h3>
        <%= @blog.content %>
    </h3>
    
    <div>
        <% if @blog.user == current_user %>
            <%= link_to "EDIT", edit_blog_path(@blog.id) %>
            <%= link_to 'DELETE', blog_path(@blog.id), method: :delete,data: { confirm: '本当に削除していいですか？' } %>
        <% end %>
    
<% unless @blog.user == current_user %>
    <% if @favorite.present? %>
        <%= link_to 'お気に入り解除する', favorite_path(blog_id: @blog.id), method: :delete, class: 'btn btn-danger' %>
    <% else %>
        <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
    <% end %>
    <p id="notice"><%= notice %></p>
<% end %>
<p>
  <strong>Image</strong>
  <%= image_tag @blog.image %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>
    </div>
</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :contact_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :contact_email %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :contact_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.content %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Content:</strong>
  <%= @contact.content %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/favorites/index.html.erb
<div class="container">
  <table>
    <tr>
      <th>タイトル</th>
      <th>内容</th>
    </tr>
    <% @favorites.each do |favorite| %>
      <tr>
        <td><%= favorite.blog.title %></td>
        <td><%= favorite.blog.content %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/home/about.html.erb
<div class="text-center row">
    <div class="col-lg-8 col-lg-offset-2 centered">
                <div class ="jumbotron" style ="height:450px; color:white;
                background:url(/assets/contact-bg.jpg);  background-size:cover;">
                    <h1>このサイトについて?</h1>
                    <h2>短い日記、ブログを自由にかけます</h2>
                    <h2>それを公開できます</h2>
                    <p>このサイトはユーザー登録をしてログインしてから利用できます
                        まずはじめにユーザー登録を行って下さい</p>
    </div><!-- /col-lg-8 -->
</div>

app/views/home/top.html.erb
<div class ="jumbotron text-center"style ="height:300px; color:white; text-shadow: 2px 2px 4px #666; 
 background:url(/assets/about-bg.jpg);  background-size:cover;">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 centered">
            <h1>ブログ投稿アプリ</h1>
            <h2>ここに自由に投稿しよう</h2>
        </div>
    </div>
</div> 

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true, url: user_choose_new_or_edit) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2 class="alert alert-warning" role="alert"><%= @user.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li class="alert alert-warning" role="alert"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="user_name">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="user_email">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="user_password">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="user_password_confirmation">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="new_icon">
    <p class="new_icon_lable"><%= form.label :icon %></p>
    <p class="new_icon_image"><%= form.file_field :icon, id: :@user_icon %></p>
    <%= image_tag(@user.icon.url) if @user.icon.url %>
    <%= form.hidden_field :icon_cache %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to "ユーザー詳細画面にもどる", user_path(@user.id) %>

app/views/users/confirm.html.erb
<h1>確認画面</h1>
<%= form_with(model: @user, url: users_path, local: true) do |form| %>
  <%= form.hidden_field :name %>
  <%= form.hidden_field :email %>
  <%= form.hidden_field :password %>
  <%= form.hidden_field :password_confirmation %>
  <%= hidden_field_tag :"cache[image]",@user.icon.cache_name %>

  <p>名前:<%= @user.name %></p>
  <p>メールアドレス:<%= @user.email %></p>
  <p>パスワード:<%= @user.password %></p>
  <p>
    <%= image_tag(@user.icon.url) %>
  </p>
  <%= form.submit "登録する" %>
<% end %>

<%= form_with(model:@user, url:new_user_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :name %>
  <%= form.hidden_field :email %>
  <%= hidden_field_tag :"cache[icon]",@user.icon.cache_name %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/users/edit.html.erb
<h2>ユーザー情報を編集する</h2>

<%= render 'form' %>

app/views/users/new.html.erb
<div class =" text-center">
  <h1>Sign up</h1>

  <%= form_with(model: @user, local: true, url:confirm_users_path) do |form| %>

    <div class="container">
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2 class="alert alert-warning" role="alert"><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
          <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li class="alert alert-warning" role="alert"><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="user_name">
        <%= form.label :name %>
        <%= form.text_field :name %>
      </div>

      <div class="user_email">
        <%= form.label :email %>
        <%= form.email_field :email %>
      </div>

      <div class="user_password">
        <%= form.label :password %>
        <%= form.password_field :password %>
      </div>

      <div class="user_password_confirmation">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation %>
      </div>

      <div class="new_icon">
        <p class="new_icon_lable"><%= form.label :icon_image %></p>
        <p class="new_icon_image"><%= form.file_field :icon, id: :@user_icon %></p>
        <%= image_tag(@user.icon_image.url) if @user.icon.url %>
        <%= form.hidden_field :icon_cache %>
      </div>
      <div class="actions">
        <%= form.submit "Create my account" %>
      </div>
    </div>

<% end %>
</div>

app/views/users/show.html.erb
<div class =" text-center">
<h1><%= @user.name %>のページ</h1>

<p class="user_infomation_image">
  <%= image_tag @user.icon %>
</p>

<p>メールアドレス: <%= @user.email %></p>

<p class="user_infomation">
  <%= link_to 'ユーザー情報を編集', edit_user_path(@user.id), class: 'btn btn-warning' %>
</p>

<h1><%= @user.name %>のお気に入りブログ</h1>

<% @favorites.each do |favorite| %>
 <tr>
      <td class="index_favorite_blog"><%= favorites_blog.user.name %></td>
      <td class="index_favorite_blog"><%= favorites_blog.title %></td>
      <td class="index_favorite_blog"><%= favorites_blog.content %></td>
      <td class="index_favorite_blog_image">
        <%= image_tag favorites_blog.image %>
      </td>
    </tr>
  <% end %>

</div>